### ISSUE TITLE
Prometheus job

### ISSUE THREAD

**Issue by agustinlacorazza** [enix/hpmsa_exporter#1]
HI 
could you add the Prometheus configuration that you are using to connect to your service? 

Thanks!

**Comment by NaPs** [comment]
Hi Agustin,

Here is the prom config I use for this exporter:

```
- job_name: 'msa'
  scrape_interval: 60s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - '/etc/prom-conf/targets/msa/*.json'
```

And here is an example of target json:

```
[
  {
    "targets": [ 
      "1.2.3.4:8000" ],
    "labels": {
      "env": "prod",
      "job": "msa",
      "name": "storage-x"
    }
  }
]
```

Is this helping you?

Antoine
